### ISSUE TITLE
testing party bug: can't see accounts of other posters or other user profiles

### ISSUE THREAD

**Issue by maludee** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3#126]
not sure if this is really a bug or if I just couldn't figure out how, but:
- other posters profiles are not clickable eg on this post: http://taxiapp2.us-east-1.elasticbeanstalk.com/forum/post/3/ 
- couldn't see any other way to find other users' profiles

**Comment by da2853** [comment]
Resolved
