### ISSUE TITLE
Testing Party: Unable to edit the profile form

### ISSUE THREAD

**Issue by aru456** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3#128]
<img width="773" alt="image" src="https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/60089478/f1f46d74-325d-4c0c-a9ef-8870245c82fe">
<img width="727" alt="image" src="https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/60089478/e9575589-5a6a-424f-a642-0c3e0f230b29">

**Comment by da2853** [comment]
fixed
