### ISSUE TITLE
Testing Party: No validation for comments input

### ISSUE THREAD

**Issue by aru456** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3#131]
A user should not be able to submit empty comments or just comments having spaces or without any content

<img width="1047" alt="image" src="https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/60089478/0c492417-d660-4ab8-8a2d-d2f4b5241e76">

At max week has 168hrs, I think it's always best to validate inputs in the front and put max values

<img width="843" alt="image" src="https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/60089478/ba288a9d-2328-4dfa-8308-5a05530bdbcd">

**Comment by da2853** [comment]
Fixed with PR 157
