### ISSUE TITLE
Testing Party: Forbidden 403 Error When Updating Profile Details

### ISSUE THREAD

**Issue by vamshinaik309** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3#145]
- When attempting to update my profile details after logging in, I encounter a Forbidden 403 error page.

![team3_6](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/46342370/3caa62f9-f489-4dfd-baec-ac21cfff671c)

**Comment by da2853** [comment]
fixed
