### ISSUE TITLE
Testing party: Error while updating the Email ID

### ISSUE THREAD

**Issue by NaveenAlampally** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3#146]
When I am updating the email address in the edit profile, I am getting the 403 error.

Before change:
![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/157057755/c8eccf7e-fa12-4e06-bf0a-ccd9efda069f)

After Change:
![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/157057755/0aec4d80-642e-464a-a088-d6a15f91c96b)

Error:
![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/157057755/f05f3693-30ec-4d99-a2ca-7389ff1de85d)

**Comment by da2853** [comment]
fixed
