### ISSUE TITLE
Testing Party: Phone Number Input Validation Issue

### ISSUE THREAD

**Issue by NaveenAlampally** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3#147]
**The input field is accepting more than 10 characters, and it's allowing both numbers and letters to be entered as the phone number.**

![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/157057755/ba04763f-ac49-48e5-8d6b-2a257fb54253)

![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3/assets/157057755/8ae89cf9-e92e-42b8-9405-2c4127b46b64)

**Comment by da2853** [comment]
Resolved
